version: '2.1'
orbs:
  gradle: circleci/gradle@3.0.0
  gh: circleci/github-cli@2.2.0
workflows:
  test-and-release:
    jobs:
      - gradle/test
#      - gh/release:
#          notes-file: changelog.md
#          tag: 1.0.1
#          title: The initial release
#          requires:
#            - gradle/test
#          context:
#            - GITHUB_CREDS
#          filters:
#            branches:
#              only:
#                - main

